apiVersion: v2
name: steadybit-extension-kafka
description: Steadybit scaffold extension Helm chart for Kubernetes.
version: 1.0.22
appVersion: v1.1.1
home: https://www.steadybit.com/
icon: https://steadybit-website-assets.s3.amazonaws.com/logo-symbol-transparent.png
maintainers:
  - email: antoine@steadybit.com
    name: achoimet
sources:
  - https://github.com/steadybit/extension-kafka
annotations:
  artifacthub.io/images: |
    - name: logo
      image: https://steadybit-website-assets.s3.amazonaws.com/logo-symbol-transparent.png
  artifacthub.io/links: |-
    - name: Steadybit website
      url: https://www.steadybit.com
    - name: Steadybit reliability hub
      url: https://hub.steadybit.com
dependencies:
  - name: extensionlib
    version: ^1.4.4
    repository: https://steadybit.github.io/helm-charts
