name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  extension-ci:
    uses: steadybit/extension-kit/.github/workflows/reusable-extension-ci.yml@main
    with:
      go_version: '1.24'
      runs_on: steadybit_runner_ubuntu_latest_4cores_16GB
      build_linux_packages: true
      VERSION_BUMPER_APPID: ${{ vars.GH_APP_STEADYBIT_APP_ID }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      PAT_TOKEN_EXTENSION_DEPLOYER: ${{ secrets.PAT_TOKEN_EXTENSION_DEPLOYER }}
      MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      MAVEN_GPG_PRIVATE_KEY_PASSWORD: ${{ secrets.MAVEN_GPG_PRIVATE_KEY_PASSWORD }}
      PAT_TOKEN_GORELEASER: ${{ secrets.PAT_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      VERSION_BUMPER_SECRET: ${{ secrets.GH_APP_STEADYBIT_PRIVATE_KEY }}
      GCP_ARTIFACT_REGISTRY_IDENTITY_PROVIDER: ${{ secrets.GCP_ARTIFACT_REGISTRY_IDENTITY_PROVIDER }}

  build-consumer-image:
    name: Build Dummy Consumer Image
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96
        with:
          images: ghcr.io/${{ github.repository }}/dummyconsumer

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        with:
          context: ./test-dataset/dummyconsumer/
          file: ./test-dataset/dummyconsumer/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/dummyconsumer:main
          labels: ${{ steps.meta.outputs.labels }}
